version: "3"
services:
  app:
    container_name: app-container
    image: raindrops-image
    restart: always
    build: .
    depends_on:
      - json-server
    environment:
      - DB_HOST=json-server
    ports:
      - "80:80"

  json-server:
    container_name: jsonservercontainer
    image: json-server-image:latest
    build: ./db
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/data/db.json
    command: json-server --watch /data/db.json --host 0.0.0.0
